using System;
using UnityEngine;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class NinjaGameManagerModel {
    [RealtimeProperty(1, true, true)] uint   _gameState;
    [RealtimeProperty(2, true, true)] private byte[] _startTimeBytes = new byte[0];

    public double startTime {
        get {
            return BitConverter.ToDouble(startTimeBytes, 0);
        }
        set {
            startTimeBytes = BitConverter.GetBytes(value);
        }
    } 
}
/* ----- Begin Normal Autogenerated Code ----- */
public partial class NinjaGameManagerModel : IModel {
    // Properties
    public uint gameState {
        get { return _cache.LookForValueInCache(_gameState, entry => entry.gameStateSet, entry => entry.gameState); }
        set { if (value == gameState) return; _cache.UpdateLocalCache(entry => { entry.gameStateSet = true; entry.gameState = value; return entry; }); FireGameStateDidChange(value); }
    }
    public byte[] startTimeBytes {
        get { return _cache.LookForValueInCache(_startTimeBytes, entry => entry.startTimeBytesSet, entry => entry.startTimeBytes); }
        set { if (value == startTimeBytes) return; _cache.UpdateLocalCache(entry => { entry.startTimeBytesSet = true; entry.startTimeBytes = value; return entry; }); FireStartTimeBytesDidChange(value); }
    }
    
    // Events
    public delegate void GameStateDidChange(NinjaGameManagerModel model, uint value);
    public event         GameStateDidChange gameStateDidChange;
    public delegate void StartTimeBytesDidChange(NinjaGameManagerModel model, byte[] value);
    public event         StartTimeBytesDidChange startTimeBytesDidChange;
    
    // Delta updates
    private struct LocalCacheEntry {
        public bool   gameStateSet;
        public uint   gameState;
        public bool   startTimeBytesSet;
        public byte[] startTimeBytes;
    }
    
    private LocalChangeCache<LocalCacheEntry> _cache;
    
    public NinjaGameManagerModel() {
        _cache = new LocalChangeCache<LocalCacheEntry>();
    }
    
    // Events
    public void FireGameStateDidChange(uint value) {
        try {
            if (gameStateDidChange != null)
                gameStateDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    public void FireStartTimeBytesDidChange(byte[] value) {
        try {
            if (startTimeBytesDidChange != null)
                startTimeBytesDidChange(this, value);
        } catch (System.Exception exception) {
            Debug.LogException(exception);
        }
    }
    
    // Serialization
    enum PropertyID {
        GameState = 1,
        StartTimeBytes = 2,
    }
    
    public int WriteLength(StreamContext context) {
        int length = 0;
        
        if (context.fullModel) {
            // Mark unreliable properties as clean and flatten the in-flight cache.
            // TODO: Move this out of WriteLength() once we have a prepareToWrite method.
            _gameState = gameState;
            _startTimeBytes = startTimeBytes;
            _cache.Clear();
            
            // Write all properties
            length += WriteStream.WriteVarint32Length((uint)PropertyID.GameState, _gameState);
            length += WriteStream.WriteBytesLength((uint)PropertyID.StartTimeBytes, _startTimeBytes.Length);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.gameStateSet)
                    length += WriteStream.WriteVarint32Length((uint)PropertyID.GameState, entry.gameState);
                if (entry.startTimeBytesSet)
                    length += WriteStream.WriteBytesLength((uint)PropertyID.StartTimeBytes, entry.startTimeBytes.Length);
            }
        }
        
        return length;
    }
    
    public void Write(WriteStream stream, StreamContext context) {
        if (context.fullModel) {
            // Write all properties
            stream.WriteVarint32((uint)PropertyID.GameState, _gameState);
            stream.WriteBytes((uint)PropertyID.StartTimeBytes, _startTimeBytes);
        } else {
            // Reliable properties
            if (context.reliableChannel) {
                LocalCacheEntry entry = _cache.localCache;
                if (entry.gameStateSet || entry.startTimeBytesSet)
                    _cache.PushLocalCacheToInflight(context.updateID);
                
                if (entry.gameStateSet)
                    stream.WriteVarint32((uint)PropertyID.GameState, entry.gameState);
                if (entry.startTimeBytesSet)
                    stream.WriteBytes((uint)PropertyID.StartTimeBytes, entry.startTimeBytes);
            }
        }
    }
    
    public void Read(ReadStream stream, StreamContext context) {
        bool gameStateExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.gameStateSet);
        bool startTimeBytesExistsInChangeCache = _cache.ValueExistsInCache(entry => entry.startTimeBytesSet);
        
        // Remove from in-flight
        if (context.deltaUpdatesOnly && context.reliableChannel)
            _cache.RemoveUpdateFromInflight(context.updateID);
        
        // Loop through each property and deserialize
        uint propertyID;
        while (stream.ReadNextPropertyID(out propertyID)) {
            switch (propertyID) {
                case (uint)PropertyID.GameState: {
                    uint previousValue = _gameState;
                    
                    _gameState = stream.ReadVarint32();
                    
                    if (!gameStateExistsInChangeCache && _gameState != previousValue)
                        FireGameStateDidChange(_gameState);
                    break;
                }
                case (uint)PropertyID.StartTimeBytes: {
                    byte[] previousValue = _startTimeBytes;
                    
                    _startTimeBytes = stream.ReadBytes();
                    
                    if (!startTimeBytesExistsInChangeCache && _startTimeBytes != previousValue)
                        FireStartTimeBytesDidChange(_startTimeBytes);
                    break;
                }
                default:
                    stream.SkipProperty();
                    break;
            }
        }
    }
}
/* ----- End Normal Autogenerated Code ----- */
